# Tensors (the learning part)

In [13]:
import numpy as np
import torch

In [14]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

or

In [15]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [16]:
x_ones = torch.ones_like(x_data) # new array filled with ones, same shape as x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # Returns a tensor with the same size as input that is filled with random numbers
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8224, 0.3485],
        [0.2065, 0.1136]]) 



In [17]:
shape = (2,3,) # tuple of ints
rand_tensor = torch.rand(shape) # creates a tensor of the given shape filled with random numbers from a uniform distribution 
ones_tensor = torch.ones(shape) # creates a tensor of the given shape filled with ones 
zeros_tensor = torch.zeros(shape) # creates a tensor of the given shape filled with zeros       

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8700, 0.9390, 0.7989],
        [0.9116, 0.8752, 0.2996]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

In [18]:
tensor = torch.rand(3,4) # .rand creates a tensor filled with random numbers from a uniform distribution 

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors


There are alot of tensor operations.
By default they are created on the CPU. 
You move them to the GPU or any other accelerator with the ```.to``` method

In [19]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


Some cool checks you can do in torch:

In [20]:
print(f"Is CUDA available? {torch.cuda.is_available()}")
print(f"Number of CUDA devices: {torch.cuda.device_count()}")
print(f"Current CUDA device: {torch.cuda.current_device()}")
print(f"CUDA device name: {torch.cuda.get_device_name(0)}")

Is CUDA available? True
Number of CUDA devices: 1
Current CUDA device: 0
CUDA device name: NVIDIA GeForce RTX 3090


Standard numpy-like indexing and slicing:

In [ ]:
# indexing and slicing means you can grab specific parts of tensors using standard Python slicing and indexing syntax
tensor = torch.ones(4, 4) # create a 4x4 tensor filled with ones
print(f"First row: {tensor[0]}") 
print(f"First column: {tensor[:, 0]}") 
tensor[:,1] = 0 # change the values of the second column to zeros
print(f"Tensor after changing second column to zeros: \n{tensor}")

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Tensor after changing second column to zeros: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension.

note that you cant concatenate tensors of different shapes, so for the example below we are concatenating the same tensor 3 times along the columns (dim=1)
we cant concatenate along the rows (dim=0) because the number of columns would not match or (dim=2) because the number of dimensions would not match and so on.

In [27]:
concat_tensors = torch.cat([tensor, tensor, tensor], dim=1)
print(concat_tensors)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


Arithmetic operations



In [28]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# @ is the infix operator for matrix multiplication in Python, and it is equivalent to torch.matmul()   
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])